# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         CGI-Pure
version:      1.0
version_from: Pure.pm
installdirs:  site
requires:
    URI::Escape:                   3.22

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
